-- AlterEnum
BEGIN;
CREATE TYPE "CampusLocation_new" AS ENUM ('MILLS_LIBRARY', 'THODE_LIBRARY', 'MUSC', 'GILMOUR_HALL', 'UNIVERSITY_HALL', 'HAMILTON_HALL', 'CHESTER_NEW_HALL', 'TSH', 'KTH', 'LRW', 'REFECTORY', 'THE_HUB', 'BSB', 'ABB', 'GSB', 'LIFE_SCIENCES', 'PSYCHOLOGY', 'MDCL', 'IAHS', 'JHE', 'HATCH', 'ETB', 'ITB', 'DSB', 'DBAC', 'IVOR_WYNNE', 'RON_JOYCE_STADIUM', 'COMMONS_BUILDING', 'PGCLL', 'LES_PRINCE', 'BATES', 'BRANDON_HALL', 'WOODSTOCK_HALL', 'HEDDEN_HALL', 'MARY_KEYES', 'MATTHEWS_HALL', 'MOULTON_HALL', 'WALLINGFORD_HALL', 'MCKAY_HALL', 'WHIDDEN_HALL', 'EDWARDS_HALL', 'HSR_BUS', 'CAMPUS_BUS_TERMINAL', 'OUTDOOR_CAMPUS_GROUNDS', 'OTHER', 'UNKNOWN');
ALTER TABLE "Post" ALTER COLUMN "location" TYPE "CampusLocation_new" USING ("location"::text::"CampusLocation_new");
ALTER TYPE "CampusLocation" RENAME TO "CampusLocation_old";
ALTER TYPE "CampusLocation_new" RENAME TO "CampusLocation";
DROP TYPE "public"."CampusLocation_old";
COMMIT;

